# -*- coding: utf-8 -*-
"""claimbuster_fact_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQec1kMmq1l44Mla9Sk87-rMyqeYOLHB
"""

import requests
import json

def is_fact_check_claimbuster(claim):

    api_key = "e0a48310ef5c47c296a9d265e4180341"
    input_claim = claim

    # Define the endpoint (url) with the claim formatted as part of it, api-key (api-key is sent as an extra header)
    api_endpoint = f"https://idir.uta.edu/claimbuster/api/v2/query/fact_matcher/{input_claim}"
    request_headers = {"x-api-key": api_key}

    # Send the GET request to the API and store the api response
    api_response = requests.get(url=api_endpoint, headers=request_headers)

    # Print out the JSON payload the API sent back
    print(api_response.json())

    data = api_response.json()  # Correctly call json() here to get the dictionary

    # Extract the required fields (truth_rating, claim, url)
    result = [
        {
            "truth_rating": entry["truth_rating"],
            "claim": entry["claim"],
            "url": entry["url"]
        }
        for entry in data["justification"]  # Now we can access 'justification' correctly
    ]



fact_check_response = is_fact_check_claimbuster("Biden is president")